version: '3'

networks:
  islab:
    external:
      name: islab

services:
  dapp.islab.re.kr:
    ports:
      - 4000:4000
    networks:
      islab:
        ipv4_address: 172.30.1.109
    extra_hosts:
      - "orderer0.islab.re.kr:172.30.1.100"
      - "orderer1.islab.re.kr:172.30.1.101"
      - "orderer2.islab.re.kr:172.30.1.102"
      - "ca.service.islab.re.kr:172.30.1.110"
      - "tlsca.service.islab.re.kr:172.30.1.111"
      - "couchdb.peer0.service.islab.re.kr:172.30.1.112"
      - "peer0.service.islab.er.kr:172.30.1.120"
      - "ca.blockchain.islab.re.kr:172.30.1.210"
      - "tlsca.blockchain.islab.re.kr:172.30.1.211"
      - "couchdb.peer0.blockchain.islab.re.kr:172.30.1.212"
      - "peer0.blockchain.islab.re.kr:172.30.1.220"