version: 1.5.5
port: 7055
cors:
  enabled: false
  origins:
    - "*"

debug: false
crlsizelimit: 512000

tls:
  enabled: true
  certfile: /etc/hyperledger/fabric-ca-server-config/tlsca.service.islab.re.kr-cert.pem
  keyfile: /etc/hyperledger/fabric-ca-server-config/priv_sk
  clientauth:
    type: noclientcert
    certfiles:

ca:
  name: tlsca.service.islab.re.kr
  keyfile: /etc/hyperledger/fabric-ca-server-config/priv_sk
  certfile: /etc/hyperledger/fabric-ca-server-config/tlsca.service.islab.re.kr-cert.pem
  chainfile:
  reenrollIgnoreCertExpiry: false

crl:
  expiry: 24h

registry:
  maxenrollments: -1
  identities:
    - name: admin
      pass: adminpw
      type: client
      affiliation: ""
      attrs:
        hf.Registrar.Roles: "*"
        hf.Registrar.DelegateRoles: "*"
        hf.Revoker: true
        hf.IntermediateCA: true
        hf.GenCRL: true
        hf.Registrar.Attributes: "*"
        hf.AffiliationMgr: true

db:
  type: sqlite3
  datasource: fabric-ca-server.db
  tls:
    enabled: false
    certfiles:
    client:
      certfile:
      keyfile:

ldap:
  enabled: false
  url: ldap://<adminDN>:<adminPassword>@<host>:<port>/<base>
  tls:
    certfiles:
    client:
      certfile:
      keyfile:
  attribute:
    names: ["uid", "member"]
    converters:
      - name:
        value:
    maps:
      groups:
        - name:
          value:

affiliations:
  service:

signing:
  default:
    usage:
      - digital signature
    expiry: 8760h
  profiles:
    ca:
      usage:
        - cert sign
        - crl sign
      expiry: 43800h
      caconstraint:
        isca: true
        maxpathlen: 0
    tls:
      usage:
        - signing
        - key encipherment
        - server auth
        - client auth
        - key agreement
      expiry: 8760h

csr:
  cn: tlsca.service.islab.re.kr
  keyrequest:
    algo: ecdsa
    size: 256
  names:
    - C: US
      ST: California
      L: San Francisco
      O: service.islab.re.kr
      OU:
  hosts:
    - tlsca.service.islab.re.kr
    - localhost
  ca:
    expiry: 131400h
    pathlength: 1

idemix:
  rhpoolsize: 1000
  nonceexpiration: 15s
  noncesweepinterval: 15m

bccsp:
  default: SW
  sw:
    hash: SHA2
    security: 256
    filekeystore:
      keystore: msp/keystore

cacount:
cafiles:

intermediate:
  parentserver:
    url:
    caname:
  enrollment:
    hosts:
    profile:
    label:
  tls:
    certfiles:
    client:
      certfile:
      keyfile:

cfg:
  identities:
    passwordattempts: 10

operations:
  listenAddress: 127.0.0.1:9443
  tls:
    enabled: false
    cert:
      file:
    key:
      file:
    clientAuthRequired: false
    clientRootCAs:
      files: []

metrics:
  provider: disabled
  statsd:
    network: udp
    address: 127.0.0.1:8125
    writeInterval: 10s
    prefix: server
