# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
General:
  ListenAddress: 0.0.0.0
  ListenPort: 7050

  # TLS: TLS settings for the GRPC server.
  TLS:
    Enabled: true
    PrivateKey: crypto-config/ordererOrganizations/islab.re.kr/orderers/orderer0.islab.re.kr/tls/server.key
    Certificate: crypto-config/ordererOrganizations/islab.re.kr/orderers/orderer0.islab.re.kr/tls/server.crt
    RootCAs:
      - crypto-config/ordererOrganizations/islab.re.kr/orderers/orderer0.islab.re.kr/tls/ca.crt
      - crypto-config/peerOrganizations/service.islab.re.kr/peers/peer0.service.islab.re.kr/tls/ca.crt
      - crypto-config/peerOrganizations/blockchain.islab.re.kr/peers/peer0.blockchain.islab.re.kr/tls/ca.crt
    ClientAuthRequired: true
    ClientRootCAs:
      - crypto-config/ordererOrganizations/islab.re.kr/users/Admin@islab.re.kr/tls/ca.crt

  # Keepalive settings for the GRPC server.
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
  Cluster:
    ClientCertificate: crypto-config/ordererOrganizations/islab.re.kr/users/Admin@islab.re.kr/tls/client.crt
    ClientPrivateKey: crypto-config/ordererOrganizations/islab.re.kr/users/Admin@islab.re.kr/tls/client.key
    DialTimeout: 5s
    RPCTimeout: 7s
    RootCAs:
      - crypto-config/ordererOrganizations/islab.re.kr/users/Admin@islab.re.kr/tls/ca.crt
    ReplicationBufferSize: 20971520
    ReplicationPullTimeout: 5s
    ReplicationRetryTimeout: 5s

  BootstrapMethod: file
  BootstrapFile: block/genesis.block

  LocalMSPDir: crypto-config/ordererOrganizations/service.islab.re.kr/orderers/orderer0.islab.re.kr/msp
  LocalMSPID: serviceMSP

  Profile:
    Enabled: false
    Address: 0.0.0.0:6060

  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:

    PKCS11:
      Library:
      Label:
      Pin:
      Hash:
      Security:
      FileKeyStore:
        KeyStore:

  Authentication:
    TimeWindow: 15m

################################################################################
#
#   SECTION: File Ledger
#
#   - This section applies to the configuration of the file or json ledgers.
#
################################################################################
FileLedger:
  Location: /var/hyperledger/production/orderer
  Prefix: hyperledger-fabric-ordererledger

################################################################################
#
#   SECTION: Kafka
#
#   - This section applies to the configuration of the Kafka-based orderer, and
#     its interaction with the Kafka cluster.
#
################################################################################
Kafka:
  Retry:
    ShortInterval: 5s
    ShortTotal: 10m
    LongInterval: 5m
    LongTotal: 12h
    NetworkTimeouts:
      DialTimeout: 10s
      ReadTimeout: 10s
      WriteTimeout: 10s
    Metadata:
      RetryBackoff: 250ms
      RetryMax: 3
    Producer:
      RetryBackoff: 100ms
      RetryMax: 3
    Consumer:
      RetryBackoff: 2s
  Topic:
    ReplicationFactor: 3
  Verbose: false

  TLS:
    Enabled: false
    PrivateKey:
    Certificate:
    RootCAs:

  SASLPlain:
    Enabled: false
    User:
    Password:

  Version:

################################################################################
#
#   Debug Configuration
#
#   - This controls the debugging options for the orderer
#
################################################################################
Debug:
  BroadcastTraceDir:
  DeliverTraceDir:

################################################################################
#
#   Operations Configuration
#
#   - This configures the operations server endpoint for the orderer
#
################################################################################
Operations:
  ListenAddress: 127.0.0.1:8443

  TLS:
    Enabled: false
    Certificate:
    PrivateKey:
    ClientAuthRequired: false
    ClientRootCAs: []

################################################################################
#
#   Metrics  Configuration
#
#   - This configures metrics collection for the orderer
#
################################################################################
Metrics:
  Provider: disabled

  Statsd:
    Network: udp
    Address: 127.0.0.1:8125
    WriteInterval: 30s
    Prefix:

################################################################################
#
#   Consensus Configuration
#
#   - This section contains config options for a consensus plugin. It is opaque
#     to orderer, and completely up to consensus implementation to make use of.
#
################################################################################
Consensus:
  WALDir: /var/hyperledger/production/orderer/etcdraft/wal
  SnapDir: /var/hyperledger/production/orderer/etcdraft/snapshot
